title:             半夜醒来
email:             xuankang.lin@gmail.com
description:       康康和冰不定期的Podcast
author:            Kang and Bing
baseurl:           "/"
url:               "https://banyexinglai.com"

logo: "/img/logo_round.png"
podcast_feed: "https://banyexinglai.podbean.com/feed.xml"


# Build settings
markdown:          kramdown
paginate:          30
paginate_path:     "/podcasts/page:num/"
plugins:
  - jekyll-paginate
