title:             半夜醒来
email:             xuankang.lin@gmail.com
description:       康康和冰不定期的Podcast
author:            Kang and Bing
baseurl:           "/"
url:               "https://banyexinglai.com"

logo: "/img/logo_round.png"
podcast_feed: "https://banyexinglai.podbean.com/feed.xml"
apple_feed: "https://itunes.apple.com/us/podcast/%E5%8D%8A%E5%A4%9C%E9%86%92%E6%9D%A5/id1451496581"


# Build settings
markdown:          kramdown
paginate:          30
paginate_path:     "/podcasts/page:num/"
plugins:
  - jekyll-paginate
