title:             半夜醒来
email:             xuankang.lin@gmail.com
description:       康康和冰不定期的Podcast
author:            Kang and Bing
baseurl:           "/"
url:               "https://banyexinglai.com"

logo: "/img/logo_round.png"

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          30
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-paginate
